jobs:
  test:
    name: Unit Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Run Clean
      run: ./gradlew clean
    - continue-on-error: true
      name: Run build compatibility test
      run: ./gradlew assembleDebug
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
